### ISSUE TITLE
Not working on TF 1.13

### ISSUE THREAD

**Issue by Corea** [uber-research/atari-model-zoo#4]

**Comment by Corea** [comment]
I think this is related to https://github.com/tensorflow/tensorflow/issues/27276.

**Comment by huckiyang** [comment]
Yes, in my case, with python=3.7, tf=1.13, CUDA=10.0 will give back
``self.seekable = file.seekable
AttributeError: 'GFile' object has no attribute 'seekable'
``

**Comment by huckiyang** [comment]
@jal278 @ruiwang2uber 
Hi Joel and Uber AI team, Do you have a plan to fix this tf-gpu>1.13 not-working issue?
Since the 2080 Ti with CUDA 10 could only work on tf-gpu>1.13, I think this issue does limit the use of this atari-zoo. The same setting works well with dopamine baseline.

**Comment by jal278** [comment]
Hi @Corea + @huckiyang -- it seems like it was related to a tensorflow bug that I believe has since been fixed? Is it now working for you?

**Comment by Corea** [comment]
I was able to run with that bug fix at that time. I'm not certain if this works with TF 1.13.2, but it should work in my guess.

**Comment by huckiyang** [comment]
@jal278 Hi Joel, I think it fixed now with conda install setting. 
` conda install -c anaconda tensorflow-gpu `
Thanks again for your attention!
